import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    deviceSizes: [640, 1080, 1920],
    imageSizes: [64, 128, 384],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    formats: ["image/avif", "image/webp"],
  },
  async redirects() {
    return [
      {
        source: "/:path*",
        has: [{ type: "host", value: "www.odisea-tours.com" }],
        destination: "https://odisea-tours.com/:path*",
        permanent: true,
      },
      { source: "/about", destination: "/team", permanent: true },
      { source: "/about-us", destination: "/team", permanent: true },
      { source: "/blog", destination: "/journal", permanent: true },
      { source: "/blog/:slug*", destination: "/journal/:slug*", permanent: true },
      { source: "/news", destination: "/journal", permanent: true },
      { source: "/news/:slug*", destination: "/journal/:slug*", permanent: true },
      { source: "/services", destination: "/tours", permanent: true },
      { source: "/sports-tours", destination: "/tours", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
      { source: "/barcelona", destination: "/destinations/barcelona", permanent: true },
      { source: "/madrid", destination: "/destinations/madrid", permanent: true },
      { source: "/valencia", destination: "/destinations/valencia", permanent: true },
      { source: "/barcelona-tours", destination: "/destinations/barcelona", permanent: true },
      { source: "/madrid-tours", destination: "/destinations/madrid", permanent: true },
      { source: "/valencia-tours", destination: "/destinations/valencia", permanent: true },
      { source: "/school-tours", destination: "/schools", permanent: true },
      { source: "/schools-tours", destination: "/schools", permanent: true },
      { source: "/youth-tours", destination: "/youth", permanent: true },
      { source: "/veteran-tours", destination: "/veterans", permanent: true },
      { source: "/veterans-tours", destination: "/veterans", permanent: true },
      { source: "/plan", destination: "/plan-your-tour", permanent: true },
      { source: "/plan-tour", destination: "/plan-your-tour", permanent: true },
      { source: "/book", destination: "/plan-your-tour", permanent: true },
      { source: "/booking", destination: "/plan-your-tour", permanent: true },
      { source: "/home", destination: "/", permanent: true },
      { source: "/index", destination: "/", permanent: true },
      { source: "/index.html", destination: "/", permanent: true },

      // Legacy WordPress slugs (sweep added 2026-04-27 for GSC 404s)
      { source: "/sample-page", destination: "/", permanent: true },
      { source: "/faqs", destination: "/faq", permanent: true },
      { source: "/contact-form", destination: "/contact", permanent: true },
      { source: "/book-now", destination: "/plan-your-tour", permanent: true },
      { source: "/quote", destination: "/plan-your-tour", permanent: true },
      { source: "/pricing", destination: "/plan-your-tour", permanent: true },
      { source: "/package", destination: "/plan-your-tour", permanent: true },
      { source: "/packages", destination: "/plan-your-tour", permanent: true },
      { source: "/testimonials", destination: "/journal", permanent: true },
      { source: "/soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/soccer-tours", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/football-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/football-tours", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/spain-soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/spain-football-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/spain-soccer", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/youth-soccer", destination: "/youth", permanent: true },
      { source: "/la-liga-tours", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/barcelona-soccer", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/madrid-soccer", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/spain", destination: "/tours", permanent: true },
      { source: "/spain-tours", destination: "/tours", permanent: true },
      { source: "/europe-tours", destination: "/tours", permanent: true },
      { source: "/tour", destination: "/tours", permanent: true },
      { source: "/tours/spain", destination: "/tours", permanent: true },
      { source: "/our-tours", destination: "/tours", permanent: true },
      { source: "/sport", destination: "/tours", permanent: true },
      { source: "/sport-tours", destination: "/tours", permanent: true },
      { source: "/sport-adventure", destination: "/tours/sport-adventure", permanent: true },
      { source: "/culture", destination: "/tours/cultural-journeys", permanent: true },
      { source: "/cultural-tours", destination: "/tours/cultural-journeys", permanent: true },
      { source: "/private-tours", destination: "/tours", permanent: true },
      { source: "/group-tours", destination: "/tours", permanent: true },
      { source: "/experience", destination: "/tours", permanent: true },
      { source: "/experiences", destination: "/tours", permanent: true },
      { source: "/ground-services", destination: "/tours", permanent: true },
      { source: "/destinations/spain", destination: "/destinations", permanent: true },
      { source: "/destinations/seville", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/destinations/sevilla", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/seville", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/sevilla", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/granada", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/bilbao", destination: "/tours/sabores-de-espana", permanent: true },
      { source: "/pamplona", destination: "/tours/sabores-de-espana", permanent: true },
      { source: "/la-masia", destination: "/journal/la-masia-la-fabrica-academies-worth-visiting", permanent: true },
    ];
  },
};

export default nextConfig;
