import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    deviceSizes: [640, 1080, 1920],
    imageSizes: [64, 128, 384],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    formats: ["image/avif", "image/webp"],
  },
  async redirects() {
    return [
      {
        source: "/:path*",
        has: [{ type: "host", value: "www.odisea-tours.com" }],
        destination: "https://odisea-tours.com/:path*",
        permanent: true,
      },
      { source: "/about", destination: "/team", permanent: true },
      { source: "/about-us", destination: "/team", permanent: true },
      { source: "/blog", destination: "/journal", permanent: true },
      { source: "/blog/:slug*", destination: "/journal/:slug*", permanent: true },
      { source: "/services", destination: "/tours", permanent: true },
      { source: "/sports-tours", destination: "/tours", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
      { source: "/barcelona", destination: "/destinations/barcelona", permanent: true },
      { source: "/madrid", destination: "/destinations/madrid", permanent: true },
      { source: "/valencia", destination: "/destinations/valencia", permanent: true },
      { source: "/barcelona-tours", destination: "/destinations/barcelona", permanent: true },
      { source: "/madrid-tours", destination: "/destinations/madrid", permanent: true },
      { source: "/valencia-tours", destination: "/destinations/valencia", permanent: true },
      { source: "/school-tours", destination: "/schools", permanent: true },
      { source: "/schools-tours", destination: "/schools", permanent: true },
      { source: "/youth-tours", destination: "/youth", permanent: true },
      { source: "/veteran-tours", destination: "/veterans", permanent: true },
      { source: "/veterans-tours", destination: "/veterans", permanent: true },
      { source: "/plan", destination: "/plan-your-tour", permanent: true },
      { source: "/plan-tour", destination: "/plan-your-tour", permanent: true },
      { source: "/book", destination: "/plan-your-tour", permanent: true },
      { source: "/booking", destination: "/plan-your-tour", permanent: true },
      { source: "/home", destination: "/", permanent: true },
      { source: "/index", destination: "/", permanent: true },
      { source: "/index.html", destination: "/", permanent: true },

      // Legacy WordPress slugs (sweep added 2026-04-27 for GSC 404s)
      { source: "/sample-page", destination: "/", permanent: true },
      { source: "/faqs", destination: "/faq", permanent: true },
      { source: "/contact-form", destination: "/contact", permanent: true },
      { source: "/book-now", destination: "/plan-your-tour", permanent: true },
      { source: "/quote", destination: "/plan-your-tour", permanent: true },
      { source: "/pricing", destination: "/plan-your-tour", permanent: true },
      { source: "/package", destination: "/plan-your-tour", permanent: true },
      { source: "/packages", destination: "/plan-your-tour", permanent: true },
      { source: "/testimonials", destination: "/journal", permanent: true },
      { source: "/soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/soccer-tours", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/football-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/football-tours", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/spain-soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/spain-football-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/spain-soccer", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/youth-soccer", destination: "/youth", permanent: true },
      { source: "/la-liga-tours", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/barcelona-soccer", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/madrid-soccer", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/spain", destination: "/tours", permanent: true },
      { source: "/spain-tours", destination: "/tours", permanent: true },
      { source: "/europe-tours", destination: "/tours", permanent: true },
      { source: "/tour", destination: "/tours", permanent: true },
      { source: "/tours/spain", destination: "/tours", permanent: true },
      { source: "/our-tours", destination: "/tours", permanent: true },
      { source: "/sport", destination: "/tours", permanent: true },
      { source: "/sport-tours", destination: "/tours", permanent: true },
      { source: "/sport-adventure", destination: "/tours/sport-adventure", permanent: true },
      { source: "/culture", destination: "/tours/cultural-journeys", permanent: true },
      { source: "/cultural-tours", destination: "/tours/cultural-journeys", permanent: true },
      { source: "/private-tours", destination: "/tours", permanent: true },
      { source: "/group-tours", destination: "/tours", permanent: true },
      { source: "/experience", destination: "/tours", permanent: true },
      { source: "/experiences", destination: "/tours", permanent: true },
      { source: "/ground-services", destination: "/tours", permanent: true },
      { source: "/destinations/spain", destination: "/destinations", permanent: true },
      { source: "/destinations/seville", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/destinations/sevilla", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/seville", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/sevilla", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/granada", destination: "/tours/flamenco-moorish-spain", permanent: true },
      { source: "/bilbao", destination: "/tours/sabores-de-espana", permanent: true },
      { source: "/pamplona", destination: "/tours/sabores-de-espana", permanent: true },
      { source: "/la-masia", destination: "/journal/la-masia-la-fabrica-academies-worth-visiting", permanent: true },

      // Journal duplicate consolidation 2026-05-02
      {
        source: "/journal/how-to-organize-youth-soccer-tour-spain-complete-guide",
        destination: "/journal/youth-soccer-tours-to-spain-complete-guide",
        permanent: true,
      },

      // GSC 5xx sweep 2026-05-05: legacy WP paths that need keep-signal 301s
      { source: "/activities", destination: "/tours", permanent: true },
      { source: "/activities/:path*", destination: "/tours", permanent: true },
      { source: "/destination", destination: "/destinations", permanent: true },
      { source: "/destination/:path*", destination: "/destinations", permanent: true },
      { source: "/terms-and-conditions", destination: "/terms", permanent: true },
      { source: "/terms-and-conditions/:path*", destination: "/terms", permanent: true },
      { source: "/european-soccer-tours/:path*", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/group-leaders", destination: "/plan-your-tour", permanent: true },
      { source: "/group-leaders/:path*", destination: "/plan-your-tour", permanent: true },

      // GSC 404 sweep 2026-04-27: actual legacy WordPress permalinks
      // NOTE: /soccer-tours-spain previously 301'd to /tours/european-soccer-tours.
      // Removed 2026-05-16 when /soccer-tours-spain became the SEO pillar page.
      { source: "/european-soccer-tours", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/travelingabroad", destination: "/tours", permanent: true },
      { source: "/trip", destination: "/tours", permanent: true },
      { source: "/trip/:path*", destination: "/tours", permanent: true },
      { source: "/tour/valencia-soccer-tour/:path*", destination: "/destinations/valencia", permanent: true },
      { source: "/tour/valencia-soccer-tour", destination: "/destinations/valencia", permanent: true },
      { source: "/tour/madrid-soccer-tour/:path*", destination: "/destinations/madrid", permanent: true },
      { source: "/tour/madrid-soccer-tour", destination: "/destinations/madrid", permanent: true },
      { source: "/tour/barcelona-soccer-tour/:path*", destination: "/destinations/barcelona", permanent: true },
      { source: "/tour/barcelona-soccer-tour", destination: "/destinations/barcelona", permanent: true },
      { source: "/tour/munich-baviera-soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/tour/munich-bavaria-soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/tour/fc-barcelona-soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/tour/netherlands-soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/tour/london-soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/tour/milan-venice-soccer-tour", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/tour/spanish-fa-madrid-soccer-tour", destination: "/destinations/madrid", permanent: true },
      { source: "/tour/valencia-cf-soccer-tour", destination: "/destinations/valencia", permanent: true },
      { source: "/destinations/spain-soccer", destination: "/tours/european-soccer-tours", permanent: true },
      { source: "/tour", destination: "/tours", permanent: true },
      { source: "/tour/:path*", destination: "/tours", permanent: true },

      // GSC indexed orphan slugs 2026-05-09: send to the complete-guide blog post
      { source: "/best-soccer-tours-spain", destination: "/journal/youth-soccer-tours-to-spain-complete-guide", permanent: true },
      { source: "/best-football-tours-spain", destination: "/journal/youth-soccer-tours-to-spain-complete-guide", permanent: true },
      { source: "/best-soccer-tour-spain", destination: "/journal/youth-soccer-tours-to-spain-complete-guide", permanent: true },
      { source: "/best-football-tour-spain", destination: "/journal/youth-soccer-tours-to-spain-complete-guide", permanent: true },

      // GSC legacy-URL cleanup 2026-06-09: WP paths still indexed, funnel corporate
      // variants to the new /corporate-retreats pillar, partnership to contact.
      { source: "/corporate-tours", destination: "/corporate-retreats", permanent: true },
      { source: "/corporate-tours/:path*", destination: "/corporate-retreats", permanent: true },
      { source: "/corporate-tour", destination: "/corporate-retreats", permanent: true },
      { source: "/corporate", destination: "/corporate-retreats", permanent: true },
      { source: "/corporate-retreat", destination: "/corporate-retreats", permanent: true },
      { source: "/company-retreats", destination: "/corporate-retreats", permanent: true },
      { source: "/company-retreat", destination: "/corporate-retreats", permanent: true },
      { source: "/team-building", destination: "/corporate-retreats", permanent: true },
      { source: "/retreats", destination: "/corporate-retreats", permanent: true },
      { source: "/partnership", destination: "/contact", permanent: true },
      { source: "/partnerships", destination: "/contact", permanent: true },
    ];
  },
};

export default nextConfig;
