export interface Tour {
  slug: string;
  chapter: string;
  title: string;
  italicTitle?: string;
  tagline: string;
  description: string;
  image: string;
  coordinates: string;
  duration: string;
  groupSize: string;
  includes: string[];
  itinerary: { day: string; title: string; detail: string; image?: string }[];
  accent: string;
  // Custom, query-targeted FAQs prepended ahead of the auto-generated set.
  // Phrased to mirror how travelers actually ask LLM search engines, with
  // entity-clear answers, so the page earns citations on those queries.
  faq?: { q: string; a: string }[];
}

export const TOURS: Tour[] = [
  {
    slug: "european-soccer-tours",
    chapter: "I",
    title: "European Soccer",
    italicTitle: "Pilgrimages",
    tagline: "Where the game still feels like religion.",
    description:
      "Matchday access no tourist buys online. Training-ground pass from academy directors we've worked with for fifteen years. Back-row seats in the press box, a pint with an old scout afterward, and a guide who remembers when Xavi was still a kid at La Masia.",
    image: "/photos/veterans-soccer-tour-camp-nou-barcelona.jpg",
    coordinates: "41.3809° N / 2.1228° E",
    duration: "6–10 nights",
    groupSize: "12–60 travelers",
    accent: "#ffb400",
    includes: [
      "La Liga match tickets (category by request)",
      "Stadium + museum tours at Camp Nou, Bernabéu, Metropolitano",
      "Training-facility access at partner academies",
      "Meet & greet opportunities with former pros",
      "Tactical session with a certified UEFA coach",
      "Four-star lodging within walking distance of each stadium",
    ],
    itinerary: [
      {
        day: "I",
        title: "Arrival · Barcelona",
        detail: "Transfer from BCN, welcome vermut on Las Ramblas, first training visit at sundown.",
        image: "/photos/veterans-soccer-tour-barcelona-la-rambla.jpg",
      },
      {
        day: "II",
        title: "Camp Nou & La Masia",
        detail: "Private stadium tour before the crowds, followed by an afternoon inside the academy grounds.",
        image: "/photos/veterans-soccer-tour-camp-nou-stadium.jpg",
      },
      {
        day: "III",
        title: "Matchday",
        detail: "Walk to the stadium with the locals, group seating together, post-match dinner at a bodega we love.",
        image: "/photos/veterans-soccer-tour-match-vs-spanish-team.jpg",
      },
      {
        day: "IV",
        title: "AVE to Madrid",
        detail: "High-speed rail in business class. Check in, afternoon at the Metropolitano museum.",
        image: "/photos/it-ave-train-madrid.jpg",
      },
      {
        day: "V",
        title: "Bernabéu Day",
        detail: "Behind-the-scenes at the rebuilt Bernabéu, evening Real Madrid fixture.",
        image: "/photos/veterans-soccer-tour-bernabeu-stadium.jpg",
      },
      {
        day: "VI",
        title: "Departure",
        detail: "Tapas brunch, airport transfer, and a photo book mailed home within the month.",
        image: "/photos/veterans-soccer-tour-happy-group.jpg",
      },
    ],
  },
  {
    slug: "cultural-journeys",
    chapter: "II",
    title: "Cultural",
    italicTitle: "Journeys",
    tagline: "Spain, with the volume turned up.",
    description:
      "Eight to twelve nights through Andalusia, the Castiles and the Basque north, built for travelers who came to Spain for something deeper than stadium queues and tapas-bar selfies. Private dinners in Triana family homes, studio time with a ceramicist in Úbeda, a dawn walk through the Alhambra before the gates open to the day-tripper crowd, the Prado with a curator who can talk you past Velázquez, Goya and El Greco without the script. Built around curiosity, paced for adults who actually want to linger over a glass of Tempranillo. Run by Spanish hosts who have been cooking with these chefs and walking with these historians for fifteen years.",
    image: "/photos/odisea-tours-group-barcelona-cathedral.jpg",
    coordinates: "37.1773° N / 3.5986° W",
    duration: "8–12 nights",
    groupSize: "10–30 travelers",
    accent: "#c05530",
    includes: [
      "Private guided visits to the Alhambra, the Mezquita, the Prado and the Sagrada Família",
      "Dawn entry to the Alhambra and Generalife gardens, before public opening",
      "Curator-led visit at the Prado in Madrid",
      "Private flamenco peña in Seville's Triana district, with the families who actually live there",
      "Private home dinner with a Sevillian host family",
      "Studio visit with a fourth-generation ceramicist in Úbeda",
      "Olive-oil tasting at a family-run mill in Jaén",
      "Pintxo route and hands-on cooking class in San Sebastián",
      "AVE high-speed rail transfers between Madrid, Andalusia and the Basque country",
      "Hand-selected boutique hotels and historic paradores",
      "Bilingual cultural historian and Odisea ground team throughout",
    ],
    itinerary: [
      {
        day: "I",
        title: "Seville",
        detail: "Arrival in Seville and check-in to a converted casa palacio in the Santa Cruz quarter. Evening tapas walk through the old Jewish quarter, then a private flamenco performance in a Triana peña the buses never find.",
        image: "/photos/it-seville-santa-cruz.jpg",
      },
      {
        day: "II",
        title: "Córdoba & the Mezquita",
        detail: "Day trip south to the old caliphate capital. A private hour inside the Mezquita before the doors open to the day-tripper crowd, then a quiet patio lunch with a Cordoban historian and a slow stroll through the Judería.",
        image: "/photos/it-cordoba-mezquita.jpg",
      },
      {
        day: "III",
        title: "Granada",
        detail: "Transfer east through endless olive country to Granada. Sunset on the Mirador de San Nicolás with the Alhambra in golden hour, then dinner of free tapas in a Realejo bar of the kind only locals know.",
        image: "/photos/it-granada-mirador.jpg",
      },
      {
        day: "IV",
        title: "Alhambra at Dawn",
        detail: "First group of the morning inside the Alhambra and the Generalife gardens. Three hours with an art historian who can read the Nasrid inscriptions to you in the languages they were written in.",
        image: "/photos/it-alhambra-dawn.jpg",
      },
      {
        day: "V",
        title: "Úbeda & Baeza",
        detail: "Day trip into the Renaissance towns of Úbeda and Baeza, a UNESCO landscape most travelers skip. Studio time with a ceramicist still firing the green glaze his family has fired for four hundred years, lunch at a working olive estate.",
      },
      {
        day: "VI",
        title: "Madrid · the Prado",
        detail: "AVE high-speed rail north to Madrid in under three hours. Afternoon at the Prado with a curator who can walk you past Velázquez, Goya and El Greco without the audio-guide script. Dinner in Lavapiés.",
        image: "/photos/it-madrid-prado.jpg",
      },
      {
        day: "VII",
        title: "San Sebastián",
        detail: "Train north to San Sebastián. Pintxo route through the old town with a Basque food writer, then a hands-on cooking class in a private chef's home above the bay.",
        image: "/photos/it-san-sebastian-pintxos.jpg",
      },
      {
        day: "VIII",
        title: "Bilbao & the Guggenheim",
        detail: "Coach west to Bilbao. Morning at the Guggenheim with a contemporary art guide, lunch at a sociedad gastronómica, departures from Bilbao airport or onward train to Barcelona.",
      },
    ],
  },
  {
    slug: "corporate-retreats",
    chapter: "III",
    title: "Corporate",
    italicTitle: "Retreats",
    tagline: "Off-sites that don't feel like off-sites.",
    description:
      "We stopped booking generic conference hotels a decade ago. Your team will plan next year's roadmap from a restored monastery in La Rioja, break bread with the winemaker, and come home actually energized. Every detail held invisible so your people can think.",
    image: "/img/tours/corporate.jpg",
    coordinates: "42.4627° N / 2.4449° W",
    duration: "3–6 nights",
    groupSize: "8–120 travelers",
    accent: "#1a1612",
    includes: [
      "Venue scouting and contracting",
      "AV, simultaneous translation, and stage build",
      "Team-building programming (hiking, cooking, sailing)",
      "Executive transfers, group coaches, private rail cars",
      "On-site producer and 24/7 incident response",
      "Full budget transparency and vendor reporting",
    ],
    itinerary: [
      {
        day: "I",
        title: "Arrival · La Rioja",
        detail: "Private transfers from Bilbao, welcome dinner at a family winery.",
        image: "/photos/it-rioja-winery.jpg",
      },
      {
        day: "II",
        title: "Work Day",
        detail: "Full-day strategic session in a monastery cloister, lunch served in the courtyard.",
        image: "/photos/it-monastery-cloister.jpg",
      },
      {
        day: "III",
        title: "Team Activity",
        detail: "Choose: hiking in Sierra de la Demanda, cooking class, or horseback through the vineyards.",
        image: "/photos/it-vineyard-hike.jpg",
      },
      {
        day: "IV",
        title: "Close & Depart",
        detail: "Morning retrospective, group photo, transfers to Madrid or Bilbao.",
        image: "/photos/it-bilbao-skyline.jpg",
      },
    ],
  },
  {
    slug: "sport-adventure",
    chapter: "IV",
    title: "Sport &",
    italicTitle: "Adventure",
    tagline: "Earned views. Earned appetites.",
    description:
      "Surf camps on the Cantabrian coast, mountain-biking the Pyrenees, sailing trips through the Balearics. Built for groups who want their days physical, their nights social, and their guides genuinely certified.",
    image: "/img/tours/adventure.jpg",
    coordinates: "43.3614° N / 4.3873° W",
    duration: "5–9 nights",
    groupSize: "8–24 travelers",
    accent: "#0e6b52",
    includes: [
      "Certified mountain and water guides",
      "All technical equipment supplied",
      "Professional safety and medical support",
      "Custom programming by ability level",
      "Hotels at the trailhead or harbor",
      "Post-activity recovery and massage options",
    ],
    itinerary: [
      {
        day: "I",
        title: "San Vicente de la Barquera",
        detail: "Arrival on the Cantabrian coast, gear fitting, sunset beach walk.",
        image: "/photos/it-cantabria-coast.jpg",
      },
      {
        day: "II",
        title: "Coastal Ride",
        detail: "Sea-kayak and cliff trek along the Costa Quebrada.",
        image: "/photos/it-sea-kayak-coast.jpg",
      },
      {
        day: "III",
        title: "Picos de Europa",
        detail: "Transfer inland, cable-car to the mountain ridge, guided hike on the Ruta del Cares.",
        image: "/photos/it-picos-de-europa.jpg",
      },
      {
        day: "IV",
        title: "Rest & Ride",
        detail: "Morning yoga, afternoon e-bike through the lower valley.",
        image: "/photos/it-ebike-valley.jpg",
      },
      {
        day: "V",
        title: "Departure",
        detail: "Farewell seafood lunch in Santander, transfers to airport or train station.",
        image: "/photos/it-santander-seafood.jpg",
      },
    ],
  },
  {
    slug: "sabores-de-espana",
    chapter: "V",
    title: "Sabores",
    italicTitle: "de España",
    tagline: "Spain, tasted slowly.",
    description:
      "Eight nights of harvest season, cava among the vineyards, a Basque cooking class with a chef who learned from his grandmother, Bodegas Marqués de Riscal inside the Gehry building, and a farewell dinner in Pamplona after a day on the Running of the Bulls route. Built for adults who came here to eat, drink, and pay attention.",
    image: "/photos/sabores-de-espana-hero.jpg",
    coordinates: "42.5801° N / 2.9033° W",
    duration: "8 nights · 9 days",
    groupSize: "20 travelers",
    accent: "#b8552f",
    faq: [
      {
        q: "Who can plan a food and wine tour of Spain for a family group or group of 20?",
        a: "Odisea Tours plans private food and wine tours of Spain for family groups, groups of friends and clubs of around 20 travelers. The Sabores de España tour runs eight nights through Barcelona, La Rioja, San Sebastián and Pamplona, with a Penedès cava winery lunch, a guided tasting at Bodegas Marqués de Riscal, a hands-on Basque cooking class, a pintxos crawl through Parte Vieja, and a private 50-seat coach with a bilingual leader. The full itinerary, dates and pace are built around your group.",
      },
      {
        q: "Can you organize a wine country and gastronomy trip to Spain for adults?",
        a: "Yes. Odisea Tours specializes in food and wine travel for adults who came to eat, drink and pay attention. We pair Rioja and Navarra wine regions with the Basque pintxos scene and Catalan cuisine, arrange winery harvest lunches, cooking classes and Michelin-level farewell dinners, and keep groups small enough to sit at one table. Tell us your dates and group size and we send a per-traveler quote within 48 hours.",
      },
    ],
    includes: [
      "Eight nights in 4-star hotels across Barcelona, Zaragoza, La Rioja, San Sebastián and Pamplona",
      "Half-day Barcelona city tour and La Boqueria market walk with a local guide",
      "Flamenco dinner show at a traditional Barcelona tablao",
      "Penedès cava winery lunch, Bodegas Marqués de Riscal guided tasting, D.O. Navarra cellar visit",
      "Hands-on Basque seafood cooking class in San Sebastián and a guided pintxos crawl through Parte Vieja",
      "Full day in Pamplona with Casco Viejo walking tour, tapas lunch on Calle Estafeta, and a farewell Navarrese dinner",
      "Guggenheim Museum guided visit and Mercado de la Ribera lunch in Bilbao",
      "Private 50-seat coach with driver and bilingual tour leader for the full nine days",
    ],
    itinerary: [
      {
        day: "I",
        title: "Barcelona · El Born",
        detail: "Arrival, transfer to the Gothic Quarter, welcome dinner at a traditional Catalan restaurant in El Born.",
        image: "/photos/it-barcelona-el-born.jpg",
      },
      {
        day: "II",
        title: "Boqueria & Tablao",
        detail: "Morning city tour through Las Ramblas and La Boqueria, lunch at Port Olímpic, flamenco dinner show at night.",
        image: "/photos/it-boqueria-market.jpg",
      },
      {
        day: "III",
        title: "Penedès → Zaragoza",
        detail: "Cava winery harvest lunch among the vineyards, then on to Zaragoza for a relaxed sunset at Basílica del Pilar.",
        image: "/photos/it-penedes-cava.jpg",
      },
      {
        day: "IV",
        title: "Harvest in La Rioja",
        detail: "Grape harvest experience at a family vineyard in Haro, five-course wine pairing lunch at the bodega.",
        image: "/photos/it-rioja-harvest.jpg",
      },
      {
        day: "V",
        title: "Marqués de Riscal",
        detail: "Guided tour and tasting inside the Frank Gehry wine resort, chuletillas al sarmiento lunch in Laguardia village.",
        image: "/photos/it-marques-riscal.jpg",
      },
      {
        day: "VI",
        title: "San Sebastián",
        detail: "Drive to the Basque coast, afternoon seafood cooking class with a local chef, guided pintxos crawl through Parte Vieja.",
        image: "/photos/it-san-sebastian-concha.jpg",
      },
      {
        day: "VII",
        title: "Pamplona · Navarra",
        detail: "Full day on the Running of the Bulls route, tapas lunch on Calle Estafeta, D.O. Navarra bodega and Navarrese farewell dinner.",
        image: "/photos/it-pamplona.jpg",
      },
      {
        day: "VIII",
        title: "Bilbao · Guggenheim",
        detail: "Guided Guggenheim visit, lunch at Mercado de la Ribera, afternoon stroll through Casco Viejo.",
        image: "/photos/it-bilbao-guggenheim.jpg",
      },
      {
        day: "IX",
        title: "Departure",
        detail: "Transfer to Bilbao airport, farewell espresso, photo book mailed home within the month.",
      },
    ],
  },
  {
    slug: "flamenco-moorish-spain",
    chapter: "VI",
    title: "Flamenco",
    italicTitle: "& Moorish Spain",
    tagline: "Andalusia, from royal Madrid to the Alhambra.",
    description:
      "Seven nights through the south. A curator-led hour at the Prado. The Mezquita of Córdoba when the tour groups haven't arrived yet. The Alcázar of Seville with an art historian who will tell you what Game of Thrones got right. A live flamenco tablao in Triana and a full day inside the Alhambra palaces at the pace they deserve. Paced for adults who want to linger.",
    image: "/photos/flamenco-moorish-spain-hero.jpg",
    coordinates: "37.1760° N / 3.5880° W",
    duration: "7 nights · 8 days",
    groupSize: "20 travelers",
    accent: "#a8391e",
    faq: [
      {
        q: "Can you organize a flamenco and tapas tour of Spain for a book club or small group?",
        a: "Yes. Odisea Tours organizes flamenco and tapas tours of Spain for book clubs, groups of friends and cultural groups. The Flamenco & Moorish Spain tour spends seven nights across Madrid, Córdoba, Sevilla and Granada with a live flamenco tablao and tapas dinner in Triana, an art historian at the Prado, the Mezquita of Córdoba, the Real Alcázar of Sevilla and a full day inside the Alhambra. Tapas evenings and the daily pace are tailored to adults who want to linger.",
      },
      {
        q: "Who plans Andalusia cultural tours with flamenco for groups of around 20?",
        a: "Odisea Tours plans private Andalusia cultural tours for groups of around 20 travelers. We combine Moorish Spain, royal Madrid and a live flamenco show with a private coach, a bilingual tour leader, 4-star boutique hotels in historic centers, and guided visits with specialist historians. Dates run year-round and every itinerary is customized to the group. Start with a free planning call or the plan-your-tour form.",
      },
    ],
    includes: [
      "Seven nights in 4-star boutique hotels in historic centers (Madrid, Córdoba, Sevilla, Granada)",
      "Prado Museum guided tour with an art historian",
      "Mezquita-Catedral of Córdoba guided visit",
      "Real Alcázar of Sevilla guided visit, the Game of Thrones palace",
      "Live flamenco show with tapas dinner at a traditional Sevilla tablao",
      "Full day inside the Alhambra and Generalife Gardens with a specialist historian",
      "Sunset at the Mirador de San Nicolás and a post-Alhambra Arab baths (hammam) decompression",
      "Private coach with driver for all transfers and a bilingual tour leader for eight days",
    ],
    itinerary: [
      {
        day: "I",
        title: "Madrid · Welcome",
        detail: "Arrival, private transfer to a hotel near Gran Vía, welcome walking tour through Madrid de los Austrias, tapas dinner.",
        image: "/photos/it-madrid-gran-via.jpg",
      },
      {
        day: "II",
        title: "The Prado",
        detail: "Morning with an art historian at the Prado, leisurely lunch in Barrio de las Letras, free afternoon in Retiro.",
        image: "/photos/it-madrid-prado.jpg",
      },
      {
        day: "III",
        title: "Córdoba · Mezquita",
        detail: "Scenic coach through La Mancha, arrival in the Jewish Quarter, guided hour inside the Mezquita.",
        image: "/photos/it-cordoba-mezquita.jpg",
      },
      {
        day: "IV",
        title: "Sevilla · Flamenco",
        detail: "Morning coach via Carmona, afternoon at the Real Alcázar, evening flamenco tablao with tapas dinner.",
        image: "/photos/it-sevilla-alcazar.jpg",
      },
      {
        day: "V",
        title: "Triana",
        detail: "Walking tour of Triana, ceramic workshop visit, Mercado de Triana lunch, free afternoon by the Guadalquivir.",
        image: "/photos/it-triana-seville.jpg",
      },
      {
        day: "VI",
        title: "Olive Country → Granada",
        detail: "Drive through the olive groves with an estate tasting, check in near the Albaicín, sunset at Mirador San Nicolás.",
        image: "/photos/it-andalusia-olive-grove.jpg",
      },
      {
        day: "VII",
        title: "The Alhambra",
        detail: "Full day inside the Nasrid Palaces and Generalife with a specialist, afternoon Arab baths, farewell dinner with live guitar.",
        image: "/photos/it-alhambra-courtyard.jpg",
      },
      {
        day: "VIII",
        title: "Departure",
        detail: "Transfer from Granada to the airport, farewell espresso, end of services.",
      },
    ],
  },
  {
    slug: "sin-traduccion",
    chapter: "VII",
    title: "Sin",
    italicTitle: "Traducción",
    tagline: "Eight nights in Spain. Zero English.",
    description:
      "Built for U.S. high school Spanish programs. Eight nights through Madrid, Valencia and Barcelona with a Spanish-speaking Odisea guide who refuses to translate. A morning at the Prado, a half day in Toledo, paella cooked from scratch in El Palmar, and the Gothic Quarter at dusk. Every meal, every guide, every market stop happens in Spanish. Your students stop reaching for the English crutch by day three.",
    image: "/photos/odisea-tours-group-barcelona-cathedral.jpg",
    coordinates: "39.4699° N / 0.3763° W",
    duration: "8 nights · 9 days",
    groupSize: "15–40 students + chaperones",
    accent: "#c8602b",
    faq: [
      {
        q: "How do I plan a Spanish immersion trip for my AP Spanish or high school Spanish class?",
        a: "Odisea Tours plans Spanish-immersion school trips through the Sin Traducción tour, built for U.S. high school and AP Spanish programs. A Spanish-only Odisea guide leads eight nights through Madrid, Valencia and Barcelona where every guide, meal and market stop happens in Spanish, including a paella cooking class taught entirely in Spanish in El Palmar. Groups run 15 to 40 students plus chaperones, one teacher goes free for every ten paid students, and students stop reaching for English by day three.",
      },
      {
        q: "I'm a school counselor taking around 30 students to Spain. What should I know?",
        a: "Odisea Tours handles U.S. school groups end to end. For a group of about 30 students that means 3-star hotels in Madrid, Valencia and Barcelona, a private coach with driver for every transfer including airport pickup and drop-off, a dedicated Odisea tour leader, daily breakfast plus welcome and farewell dinners, and a free teacher place for every ten paid students. We send a custom itinerary brief before departure and provide 24/7 on-the-ground support in Spain throughout the trip.",
      },
    ],
    includes: [
      "Eight nights in 3-star hotels in Madrid, Valencia and Barcelona",
      "Spanish-only Odisea tour leader for the full nine days",
      "Private coach with driver for every transfer, including airport pickup and drop-off",
      "Half-day Toledo excursion from Madrid",
      "Prado Museum entry and a guided visit in Spanish",
      "Albufera boat ride and a hands-on paella cooking class in El Palmar, taught entirely in Spanish",
      "Sagrada Família interior entry and a Gaudí walking route in Barcelona",
      "Free guided walks through Madrid de los Austrias, Valencia old town, Las Ramblas + La Boquería + the Gothic Quarter",
      "Daily breakfast, welcome dinner in Madrid, farewell tapas dinner in Barcelona",
      "Teacher goes free on every group of ten paid students",
    ],
    itinerary: [
      {
        day: "I",
        title: "Madrid · Bienvenida",
        detail: "MAD airport pickup by private coach, hotel check-in near Gran Vía, welcome dinner around Plaza Mayor, ground rules: solo en español from this moment forward.",
        image: "/photos/it-madrid-gran-via.jpg",
      },
      {
        day: "II",
        title: "El Prado",
        detail: "Guided morning at the Prado in Spanish, focused on Velázquez and Goya. Free afternoon walk through Madrid de los Austrias, Mercado de San Miguel for tapas at the students' own pace.",
        image: "/photos/it-madrid-prado.jpg",
      },
      {
        day: "III",
        title: "Toledo → Valencia",
        detail: "Morning coach to Toledo for a half day in the imperial city. Afternoon scenic drive through La Mancha to Valencia, evening stroll near Mercado Central.",
      },
      {
        day: "IV",
        title: "Valencia · Casco Antiguo",
        detail: "Free guided walking tour of the old town with the Odisea guide, lunch on your own at Mercado Central, afternoon at the Ciudad de las Artes y las Ciencias.",
      },
      {
        day: "V",
        title: "Albufera & Paella",
        detail: "Albufera boat ride through the rice paddies, then the marquee day: paella cooking class in a family farmhouse in El Palmar, fully in Spanish, students cook in pairs and eat what they made.",
      },
      {
        day: "VI",
        title: "Valencia → Barcelona",
        detail: "Free morning at the beach or wandering Ruzafa, midday coach up the coast to Barcelona, evening light tapas dinner near the hotel.",
      },
      {
        day: "VII",
        title: "Gaudí",
        detail: "Sagrada Família interior in the morning, Gaudí walking route past Casa Batlló and Casa Milà, evening free walk down Las Ramblas through La Boquería and the Gothic Quarter.",
        image: "/photos/it-boqueria-market.jpg",
      },
      {
        day: "VIII",
        title: "Barcelona Libre",
        detail: "Free morning for shopping, journals or a beach run. Farewell tapas dinner in El Born with the full group, certificates handed out for the students who stayed in Spanish all eight nights.",
        image: "/photos/it-barcelona-el-born.jpg",
      },
      {
        day: "IX",
        title: "Departure",
        detail: "Private coach transfer to BCN airport, end of services. Photo book mailed to the school within the month.",
      },
    ],
  },
  {
    slug: "pre-season-stages",
    chapter: "VIII",
    title: "Pre-Season",
    italicTitle: "Stages",
    tagline: "Where UK clubs build their season.",
    description:
      "Built for UK clubs running their summer block in Spain. Pick the base city, pick the length between four and fifteen nights, pick full board or half. We sort the training pitches, the friendlies against age-matched Spanish opposition, the recovery pool and the coach. Your staff coach. The lads train, play, eat, sleep. Nothing else to think about.",
    image: "/photos/preseason-action-shot-pitch.jpg",
    coordinates: "40.4168° N / 3.7038° W",
    duration: "4–15 nights",
    groupSize: "18–40 players + staff",
    accent: "#1e4d6b",
    includes: [
      "Choice of base: Madrid, Valencia, Barcelona or Málaga",
      "4 to 15 nights, full board or half board",
      "Daily access to FIFA-standard grass training pitches",
      "Two to four friendlies arranged against age-matched Spanish clubs",
      "Strength-and-conditioning gym time and pool recovery sessions",
      "Team hotel within driving distance of pitch and stadium",
      "Private coach with driver for transfers and daily pitch shuttles",
      "One Odisea contact on the ground from arrival to flight home",
    ],
    itinerary: [
      {
        day: "I",
        title: "Arrival",
        detail: "Airport pickup by private coach, transfer to the team hotel, pitch walkaround and kit drop, welcome meal and first team meeting.",
        image: "/photos/preseason-team-briefing.jpg",
      },
      {
        day: "II",
        title: "Train",
        detail: "Morning fitness work on the training pitch, afternoon technical session, gym and pool recovery before dinner.",
        image: "/photos/preseason-training-spanish-fa.jpg",
      },
      {
        day: "III",
        title: "Match",
        detail: "Light morning shakeout, pre-match meal at the hotel, evening friendly against an age-matched Spanish club, post-match recovery.",
        image: "/photos/preseason-friendly-handshake.jpg",
      },
      {
        day: "IV",
        title: "Recovery",
        detail: "Pool, stretching and a video session in the morning, optional stadium tour or beach walk in the afternoon, full board through the day.",
      },
    ],
  },
  {
    slug: "camino-de-santiago",
    chapter: "IX",
    title: "Camino de",
    italicTitle: "Santiago",
    tagline: "The last hundred kilometers, on foot.",
    description:
      "Seven nights walking the final stretch of the Camino Francés, from Sarria to the Praza do Obradoiro. Eucalyptus forests, pazos, stone bridges, and a support van following the group every step. A pulpería lunch in Melide, the Pilgrim's Mass in Santiago, and a farewell dinner at a Michelin recommended Galician restaurant. You walk, we carry your bags, pour your wine, and hand you the Compostela certificate at the Cathedral.",
    image: "/photos/camino-de-santiago-hero.jpg",
    coordinates: "42.8806° N / 8.5448° W",
    duration: "7 nights · 8 days",
    groupSize: "20 travelers",
    accent: "#4a6741",
    faq: [
      {
        q: "Who organizes Camino de Santiago group walks for parishes and church groups?",
        a: "Odisea Tours organizes Camino de Santiago group walks for parishes, church groups and faith-based organizations. We run the final 100 kilometers from Sarria to Santiago de Compostela with a specialist Galician guide walking every stage, a support van for snacks, water and optional pickups, daily luggage transfer between hand-picked rural hotels, the pilgrim credential and Compostela certificate, and attendance at the Pilgrim's Mass in Santiago Cathedral. Group prayer stops and a parish-led Mass can be arranged on request.",
      },
      {
        q: "Is Odisea Tours a Camino de Santiago group tour operator, and how does it work?",
        a: "Yes. Odisea Tours is a Spain-based Camino de Santiago group tour operator. We run guided group walks of the last 100 kilometers of the Camino Francés, the minimum distance needed to earn the Compostela, for groups of around 20 walkers. You walk, we carry the bags between hotels, follow the group with a support van, pour the Galician wine at dinner, and hand you the Compostela at the Cathedral. Dates are flexible year-round and the daily distances can be shortened with van pickups.",
      },
    ],
    includes: [
      "Seven nights in hand-picked rural hotels along the route, plus a 4-star hotel in the old town of Santiago de Compostela",
      "Specialist Camino guide walking with the group every day",
      "Full support van with snacks, water, and optional pickups on every walking stage",
      "Daily luggage transfer between hotels (one bag per pilgrim)",
      "Half-board on walking days, plus a celebratory pulpería lunch in Melide and a farewell Michelin-recommended dinner in Santiago",
      "Pilgrim credential (credencial), Compostela certificate, and Pilgrim's Mass attendance",
      "Santiago Cathedral, Museum and rooftops private guided tour on the rest day",
      "Nightly glass of Galician Albariño or Mencía with dinner, safety kit, and 24/7 Odisea Tours on-the-ground support",
    ],
    itinerary: [
      {
        day: "I",
        title: "Arrival · Sarria",
        detail: "Santiago airport pickup, transfer to Sarria, pilgrim briefing, credential handed out, welcome Galician dinner.",
        image: "/photos/it-sarria.jpg",
      },
      {
        day: "II",
        title: "Sarria → Portomarín",
        detail: "Twenty-two kilometers through eucalyptus forests and stone bridges, support van mid-route, late lunch in Portomarín.",
        image: "/photos/it-eucalyptus-camino.jpg",
      },
      {
        day: "III",
        title: "Portomarín → Palas de Rei",
        detail: "Twenty-five kilometers through rolling Galician countryside, pazos and hidden chapels, dinner and overnight.",
        image: "/photos/it-galicia-countryside.jpg",
      },
      {
        day: "IV",
        title: "Melide Pulperías",
        detail: "The longest stage (shorter fifteen-kilometer option with van pickup), pulpo a feira lunch in Melide, on to Arzúa.",
        image: "/photos/it-pulpo-melide.jpg",
      },
      {
        day: "V",
        title: "Arzúa → O Pedrouzo",
        detail: "Nineteen easy kilometers through farmland, early arrival, free afternoon, optional post-walk massage.",
        image: "/photos/it-camino-pilgrims.jpg",
      },
      {
        day: "VI",
        title: "Monte do Gozo → Santiago",
        detail: "The final twenty kilometers. First view from Monte do Gozo, triumphant entry into the Praza do Obradoiro, Compostela certificate, Pilgrim's Mass, celebratory dinner.",
        image: "/photos/it-santiago-obradoiro.jpg",
      },
      {
        day: "VII",
        title: "Santiago Cathedral",
        detail: "Rest day. Private tour of the Cathedral, Museum and rooftops, free afternoon, farewell dinner at a Michelin-recommended Galician restaurant.",
        image: "/photos/it-santiago-cathedral.jpg",
      },
      {
        day: "VIII",
        title: "Departure",
        detail: "Transfer to Santiago de Compostela airport, end of services.",
      },
    ],
  },
  {
    slug: "youth-soccer-spain-tour",
    chapter: "X",
    title: "Youth Soccer",
    italicTitle: "Spain Tour",
    tagline: "Three cities. Three clubs. One unforgettable trip.",
    description:
      "Ten days through Madrid, Valencia and Barcelona, built for youth clubs from the US, UK and Australia. Coaching from RFEF, Valencia CF and FC Barcelona staff on their own training grounds. Three friendly matches against local Spanish opposition. Stadium tours of the Bernabéu, Mestalla and Camp Nou, plus a live La Liga fixture. Built around culture and family time as much as soccer, with paella experiences, free afternoons in each city, and a Spanish guide who has been doing this since 2005.",
    image: "/photos/odisea-tours-youth-fcb-training-hero.jpg",
    coordinates: "40.4168° N / 3.7038° W",
    duration: "10 nights · 11 days",
    groupSize: "30–120 travelers",
    accent: "#ffb400",
    includes: [
      "Coaching sessions led by RFEF, Valencia CF and FC Barcelona staff at their own training grounds",
      "Three friendly matches against age-matched Spanish academy or amateur sides",
      "Stadium tours of the Santiago Bernabéu, Mestalla and Camp Nou",
      "One live La Liga fixture, category by request",
      "Four-star hotels in Madrid, Valencia and Barcelona, allocated by squad and family",
      "Daily breakfast and dinner, Valencian paella experience and authentic Madrid tapas",
      "Private coach transfers throughout, including airport pickups, inter-city transfers and match-day shuttles",
      "Odisea Tours guide on the ground for the full ten days, certificates ceremony and group photography",
    ],
    itinerary: [
      {
        day: "I",
        title: "Arrival · Madrid",
        detail: "Welcome at Madrid Barajas, transfer to the team hotel, first walk through the historic center, RFEF welcome briefing and team dinner.",
        image: "/photos/it-madrid-gran-via.jpg",
      },
      {
        day: "II",
        title: "RFEF Training & La Liga",
        detail: "Two full sessions at the Spanish FA's Las Rozas headquarters, an afternoon in Madrid, then a top-flight La Liga match under the lights.",
        image: "/photos/preseason-training-spanish-fa.jpg",
      },
      {
        day: "III",
        title: "Santiago Bernabéu",
        detail: "Behind-the-scenes tour of the home of Real Madrid, Madrid panoramic, free afternoon in Retiro Park before the transfer south to Valencia.",
        image: "/photos/veterans-soccer-tour-bernabeu-stadium.jpg",
      },
      {
        day: "IV",
        title: "Mestalla & First Match",
        detail: "Coastal transfer to Valencia, stadium tour at the Mestalla, then the first friendly against local Spanish opposition.",
        image: "/photos/veterans-soccer-tour-valencia-cf-match.jpg",
      },
      {
        day: "V",
        title: "Valencia · Paella & Match Night",
        detail: "Authentic Valencian paella experience for lunch, an afternoon by the harbour, then an evening fixture against a Valencian youth academy.",
        image: "/photos/odisea-tours-valencia-cf-coach-instructing.jpg",
      },
      {
        day: "VI",
        title: "Valencia CF Training Day",
        detail: "Two full sessions at Valencia CF's Paterna training ground, certificates ceremony in the afternoon, last evening on the Mediterranean coast.",
      },
      {
        day: "VII",
        title: "FC Barcelona at Joan Gamper",
        detail: "Transfer to Barcelona, check-in at Castelldefels, training session at Joan Gamper led by FC Barcelona coaches. Parents head to the FCB Museum.",
        image: "/photos/odisea-tours-youth-fcb-training-hero.jpg",
      },
      {
        day: "VIII",
        title: "FCB Youth & the City",
        detail: "Morning watching FC Barcelona youth fixtures, afternoon at Sagrada Família and Las Ramblas, evening La Liga F match at the Johan Cruyff Stadium.",
        image: "/photos/odisea-tours-fcb-squad-with-barca-coaches.jpg",
      },
      {
        day: "IX",
        title: "Final Training, Final Match",
        detail: "One last session under FC Barcelona coaches, free afternoon in Barcelona, and the closing fixture against a Spanish academy or amateur side.",
        image: "/photos/odisea-tours-girls-fcb-celebration-hero.jpg",
      },
      {
        day: "X",
        title: "Departure · Barcelona",
        detail: "Final breakfast together, group photograph at the hotel, staggered transfers to Barcelona–El Prat for return flights home.",
        image: "/photos/odisea-tours-youth-girls-happy.jpg",
      },
    ],
  },
  {
    slug: "tournament-experience",
    chapter: "XI",
    title: "Tournament",
    italicTitle: "Experience",
    tagline: "Knockout soccer at one of Europe's biggest youth cups.",
    description:
      "Ten days built around the Donosti Cup in San Sebastián, one of Europe's most respected youth tournaments with over 900 teams from 30+ countries. Two nights in Barcelona for a session with FC Barcelona coaches at Joan Gamper and a preparation match, six nights in San Sebastián playing the cup, then a final night back in Barcelona before flying home. Group stage, knockouts, opening and closing ceremonies, Authentics Day fan zone, and meaningful matches against international opposition every day. Built for youth clubs that want competition, not tourism.",
    image: "/photos/odisea-tours-donosti-cup-trophy-lift.jpg",
    coordinates: "43.3183° N / 1.9812° W",
    duration: "9 nights · 10 days",
    groupSize: "20–120 travelers",
    accent: "#1f4fa8",
    includes: [
      "Tournament registration, credentials, age verification and fixture allocation at the Donosti Cup",
      "Six full days at the cup: group stage, knockouts, finals, Authentics Day and closing gala",
      "Session with FC Barcelona coaches at Joan Gamper, plus a preparation match against local opposition",
      "Tournament accommodation in San Sebastián for six nights, four-star hotel in Castelldefels for three nights",
      "Full board at the Velódromo de Anoeta during the cup, breakfast and dinner at hotels in Barcelona",
      "Private coach transfers Barcelona ↔ San Sebastián, plus all training, match and tournament shuttles",
      "Odisea Tours guide on the ground for the full ten days, certificates ceremony and group photography",
      "Free time woven through the schedule for La Concha bay, Monte Igueldo, pintxos in the Old Town and Sagrada Família",
    ],
    itinerary: [
      {
        day: "I",
        title: "Arrival · Barcelona",
        detail: "Welcome at El Prat, transfer to Castelldefels, first walk along the Mediterranean coast, welcome briefing and dinner.",
        image: "/photos/preseason-team-briefing.jpg",
      },
      {
        day: "II",
        title: "FC Barcelona & Preparation",
        detail: "Morning session at Joan Gamper led by FC Barcelona coaches, afternoon in Barcelona's old town, evening preparation match against local opposition.",
        image: "/photos/odisea-tours-youth-fcb-training-hero.jpg",
      },
      {
        day: "III",
        title: "North to San Sebastián",
        detail: "Morning transfer up the coast, tournament credentials and age verification at the Reale Arena, first official cup meal at the Velódromo de Anoeta.",
        image: "/photos/odisea-tours-donosti-cup-credentials.jpg",
      },
      {
        day: "IV",
        title: "Group Stage & Opening",
        detail: "First fixtures of the Donosti Cup group stage during the day, official opening ceremony at the Reale Arena in the evening with all 900 teams presented to the city.",
        image: "/photos/odisea-tours-donosti-cup-opening.jpg",
      },
      {
        day: "V",
        title: "Group Stage Day Two",
        detail: "Full day of fixtures across the tournament's 68 fields. The afternoon brings the Donosti Authentics Cup games and the traditional coaches' match for visiting staff.",
        image: "/photos/odisea-tours-donosti-cup-coaches.jpg",
      },
      {
        day: "VI",
        title: "Final Group Stage & Fan Zone",
        detail: "Last group stage fixtures determine knockout positions. Late afternoon Authentics Day at the tournament fan zone, a celebration of the cup's thirty-plus year history.",
        image: "/photos/odisea-tours-donosti-cup-group-stage.jpg",
      },
      {
        day: "VII",
        title: "Knockouts & the City",
        detail: "Final phase fixtures begin. Between matches, time to walk La Concha bay, climb Monte Igueldo, and try the famous pintxos in the Old Town.",
        image: "/photos/odisea-tours-donosti-cup-coaching.jpg",
      },
      {
        day: "VIII",
        title: "Finals & the Gala",
        detail: "Final matches throughout the day, official tournament party and closing gala in the evening, broadcast across the city of San Sebastián.",
        image: "/photos/odisea-tours-donosti-cup-trophy-lift.jpg",
      },
      {
        day: "IX",
        title: "South to Barcelona",
        detail: "Morning transfer back to the Mediterranean, check-in at Castelldefels, closing squad dinner and certificates ceremony.",
        image: "/photos/it-cantabria-coast.jpg",
      },
      {
        day: "X",
        title: "Departure · Barcelona",
        detail: "Final breakfast together, group photograph at the hotel, staggered transfers to Barcelona–El Prat for return flights home.",
        image: "/photos/odisea-tours-youth-girls-celebrating.jpg",
      },
    ],
  },
];

export function tourBySlug(slug: string) {
  return TOURS.find((t) => t.slug === slug);
}
